server.port=8086

spring.application.name=analytics-service

spring.data.mongodb.uri=mongodb://localhost:27017/analytics_db

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

spring.kafka.properties.schema.registry.url=http://localhost:9072
spring.kafka.properties.specific.avro.reader=true

spring.ai.openai.api-key=${OPENAI_API_KEY:optional}

mongock.enabled=true
mongock.migration-scan-package=com.valka.analytics.migration
