server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5432/guild_db
spring.datasource.username=postgres
spring.datasource.password=246513

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

spring.kafka.properties.schema.registry.url=http://localhost:9081
spring.kafka.properties.specific.avro.reader=true
