server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=postgres
spring.datasource.password=246513

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

