server.port=8083
  
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=97aa126cfa981a
spring.mail.password=c77b7dae19ec1f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
