server.port=8085

spring.application.name=notification-service

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

spring.kafka.properties.schema.registry.url=http://localhost:9081

spring.kafka.properties.specific.avro.reader=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=97aa126cfa981a
spring.mail.password=c77b7dae19ec1f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
